# Allow build scripts and config to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /
COPY config /config

# Base Image
FROM quay.io/fedora-ostree-desktops/sway-atomic:43

### MODIFICATIONS
ENV APPLE_T2=1
ENV APPLE_T2_MODE=headless

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=cache,dst=/var/hypr-build,id=hyprland-build \
    /ctx/build-common.sh && /ctx/build-hyprland.sh

ARG ENABLE_VIRTIOFS=false

RUN if [ "$ENABLE_VIRTIOFS" = "true" ]; then \
      install -d -m 0755 /var/mnt/shared && \
      printf '%s\n' \
        '[Unit]' \
        'Description=VirtioFS Host Share' \
        'After=network.target' \
        '' \
        '[Mount]' \
        'What=shared' \
        'Where=/var/mnt/shared' \
        'Type=virtiofs' \
        'Options=defaults' \
        '' \
        '[Install]' \
        'WantedBy=multi-user.target' \
        > /usr/lib/systemd/system/var-mnt-shared.mount && \
      ln -s ../var-mnt-shared.mount \
        /usr/lib/systemd/system/multi-user.target.wants/var-mnt-shared.mount ; \
    fi

### LINTING
RUN bootc container lint
