# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY build_files /

# Base Image
FROM ghcr.io/ublue-os/aurora-dx:stable

### MODIFICATIONS
ENV APPLE_T2=1
ENV APPLE_T2_MODE=headless

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build-common.sh && /ctx/build-cosmic.sh

### LINTING
RUN bootc container lint
